language: cpp
compiler: gcc
install: make travis-get-deps
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
script: 
  - make CXX=g++-4.9 CC=gcc-4.9
  - ./Exec/KVEngine --run-tests
after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - rm -f KVEngine.dir/AutogenMetadata.cpp.gcda # workaround
  - lcov --directory . --capture --output-file coverage.info # capture coverage info
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter out system code
  - lcov --list coverage.info # debug before upload
  - coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info # uploads to cov
